version: '3'

services:
  db:
    container_name: provabasis
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=provabasis
    network_mode: host
